site_name: AI Systems

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md

  - System:
      - Accelerator:
          - Software Stack: system/accelerator/software-stack.md
      - vLLM:
          - Apple silicon CPU: system/vllm/applesilicon-cpu.md
          - Apple silicon GPU: system/vllm/applesilicon-gpu.md
          - vLLM Debug: system/vllm/vllm-debug.md
          - vLLM Docker: system/vllm/vllm-docker.md
          - Production Stack: system/vllm/production-stack.md
          - Architecture: system/vllm/arch-overview.md
          - vLLM Contributing: system/vllm/vllm-contributing.md
      - Tool:
          - AI Infra Engineer Toolbox: system/tool/ai-infra-engineer-toolbox.md

  - Model:
      - Transformer:
          - Tokenizer: model/transformer/tokenizer.md
      - DL:
          - Readings: model/dl/readings.md

  - Workload:
      - Agent:
          - Overview: workload/agent/agent-overview.md

  - Foundation:
      - Math:
          - Math for AI: foundation/math/math-for-ai.md
      - Algorithm:
          - DSA Overview: foundation/algorithm/dsa-overview.md
      - Programming:
          - Python for AI: foundation/programming/python-for-ai.md
          - Python Debug: foundation/programming/python-debug.md
          - C++ for AI: foundation/programming/cpp-for-ai.md
      - Design:
          - Readings: foundation/design/readings.md
      - System:
          - Readings: foundation/system/readings.md
          - Security: foundation/system/security.md
      - Tool:
          - GitHub: foundation/tool/github.md

  - KM:
      - Tool:
          - GitHub MkDocs: km/tool/github-mkdocs.md